import { Trip, Location, DashboardStats } from '@/types';

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'mock-1',
    title: 'Summer Roadtrip 2025',
    description: 'Antwerp → Paris → Lyon → Barcelona',
    start_date: '2025-07-01',
    end_date: '2025-07-14',
    cover_image: null,
    route_preference: 'avoid_tolls',
    total_km: 2847,
    route_geometry: null,
    created_at: '2025-07-01T00:00:00Z',
    updated_at: '2025-07-14T00:00:00Z',
  },
  {
    id: 'mock-2',
    title: 'Weekend in Amsterdam',
    description: 'Quick city break up north',
    start_date: '2025-05-10',
    end_date: '2025-05-12',
    cover_image: null,
    route_preference: 'allow_tolls',
    total_km: 314,
    route_geometry: null,
    created_at: '2025-05-10T00:00:00Z',
    updated_at: '2025-05-12T00:00:00Z',
  },
  {
    id: 'mock-3',
    title: 'Normandy Coast 2024',
    description: 'D-Day beaches and Mont Saint-Michel',
    start_date: '2024-08-05',
    end_date: '2024-08-18',
    cover_image: null,
    route_preference: 'allow_tolls',
    total_km: 3210,
    route_geometry: null,
    created_at: '2024-08-05T00:00:00Z',
    updated_at: '2024-08-18T00:00:00Z',
  },
];

function now() {
  return new Date().toISOString();
}

export const MOCK_LOCATIONS: Record<string, Location[]> = {
  'mock-1': [
    {
      id: 'loc-1',
      trip_id: 'mock-1',
      name: 'Antwerp, Belgium',
      latitude: 51.2194,
      longitude: 4.4025,
      country: 'Belgium',
      city: 'Antwerp',
      arrival_date: '2025-07-01',
      departure_date: '2025-07-01',
      notes: 'Starting point',
      visit_order: 0,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: 'loc-2',
      trip_id: 'mock-1',
      name: 'Paris, France',
      latitude: 48.8566,
      longitude: 2.3522,
      country: 'France',
      city: 'Paris',
      arrival_date: '2025-07-02',
      departure_date: '2025-07-04',
      notes: null,
      visit_order: 1,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: 'loc-3',
      trip_id: 'mock-1',
      name: 'Barcelona, Spain',
      latitude: 41.3851,
      longitude: 2.1734,
      country: 'Spain',
      city: 'Barcelona',
      arrival_date: '2025-07-08',
      departure_date: '2025-07-12',
      notes: null,
      visit_order: 2,
      created_at: now(),
      updated_at: now(),
    },
  ],
  'mock-2': [
    {
      id: 'loc-4',
      trip_id: 'mock-2',
      name: 'Antwerp, Belgium',
      latitude: 51.2194,
      longitude: 4.4025,
      country: 'Belgium',
      city: 'Antwerp',
      arrival_date: '2025-05-10',
      departure_date: '2025-05-10',
      notes: null,
      visit_order: 0,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: 'loc-5',
      trip_id: 'mock-2',
      name: 'Amsterdam, Netherlands',
      latitude: 52.3676,
      longitude: 4.9041,
      country: 'Netherlands',
      city: 'Amsterdam',
      arrival_date: '2025-05-10',
      departure_date: '2025-05-12',
      notes: null,
      visit_order: 1,
      created_at: now(),
      updated_at: now(),
    },
  ],
  'mock-3': [
    {
      id: 'loc-6',
      trip_id: 'mock-3',
      name: 'Caen, France',
      latitude: 49.1829,
      longitude: -0.3707,
      country: 'France',
      city: 'Caen',
      arrival_date: '2024-08-05',
      departure_date: '2024-08-07',
      notes: 'Base for the D-Day beaches',
      visit_order: 0,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: 'loc-7',
      trip_id: 'mock-3',
      name: 'Bayeux, France',
      latitude: 49.2764,
      longitude: -0.7024,
      country: 'France',
      city: 'Bayeux',
      arrival_date: '2024-08-07',
      departure_date: '2024-08-10',
      notes: 'Omaha Beach and the war cemetery',
      visit_order: 1,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: 'loc-8',
      trip_id: 'mock-3',
      name: 'Mont Saint-Michel, France',
      latitude: 48.6361,
      longitude: -1.5115,
      country: 'France',
      city: 'Mont Saint-Michel',
      arrival_date: '2024-08-10',
      departure_date: '2024-08-18',
      notes: null,
      visit_order: 2,
      created_at: now(),
      updated_at: now(),
    },
  ],
};

export function getAllMockLocations(): Location[] {
  return Object.values(MOCK_LOCATIONS).flat();
}

export const MOCK_STATS: DashboardStats = {
  countries_visited: 6,
  cities_visited: 18,
  trips_count: 3,
  total_km: 8432,
  longest_trip_km: 3210,
  longest_trip_title: 'Normandy Coast 2024',
  latest_trip: MOCK_TRIPS[0],
};
